Rankin.create(first_name: "Holly", last_name: "Zaher", birthday: "17/12/1972",  city: "Nashville", state: "TN")
Rankin.create(first_name: "Sean", last_name: "Rankin", birthday: "19/04/1974",  city: "Columbia", state: "SC")
Rankin.create(first_name: "Heather", last_name: "Akers", birthday: "27/09/1976",  city: "Denver", state: "CO")
Rankin.create(first_name: "Scott", last_name: "Rankin", birthday: "22/01/1977",  city: "Columbia", state: "SC")
Rankin.create(first_name: "Katie", last_name: "Heare", birthday: "05/12/1980",  city: "Tusla", state: "OK")
Rankin.create(first_name: "Shea", last_name: "Geisbert", birthday: "20/03/1982",  city: "Columbia", state: "SC")
Rankin.create(first_name: "Sadie", last_name: "Rankin", birthday: "13/07/1984",  city: "Columbia", state: "SC")
